/**
 * Defending champions — last season's winners, per division, for a recurring
 * tour stop.
 *
 * Read straight from `lib/data/defending-champions.json`, generated by
 * `scripts/gen-defending-champions.ts` (which holds the this-year → prior-year
 * tournament mapping and the provenance notes for every pairing).
 *
 * Build-time data rather than a runtime fetch for two reasons: prior-season
 * results are immutable, and the source stored procedure returns every division
 * of the tournament (Pro + Amateur + Junior, ≈3 MB) — over Next's 2 MB Data
 * Cache ceiling, so it could not be cached and would re-download on every
 * render. The distilled file is ~6 KB.
 *
 * Re-run the generator when the season rolls over or a mapping is corrected.
 * Stops with no mapped predecessor return [] and keep the event page's honest
 * "confirmed once last season's champions are set" fallback.
 */
import raw from "@/lib/data/defending-champions.json";

export type DefendingChampion = { division: string; name: string };

const BY_EVENT = raw as Record<string, DefendingChampion[]>;

/**
 * Last season's champions for the stop at `{year}/{slug}` — the same pair the
 * event page routes on (a curated record wins there and carries no
 * `tournament_uuid`, so year+slug is the only always-available key). Empty when
 * the stop has no mapped prior-year event.
 */
export function getDefendingChampions(year: string, slug: string): DefendingChampion[] {
  return BY_EVENT[`${year}/${slug}`] ?? [];
}
